using Application.DTOs.Auth;
using Application.Interfaces;
using Application.Interfaces.Auth;
using Domain.Identities;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;

namespace Infrastructure.Services.Auth
{
    /// <summary>
    /// Provides authentication operations such as signing in users and producing authentication tokens.
    /// </summary>
    public class AuthService : IAuthService
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ITokenService _tokenService;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthService"/> class.
        /// </summary>
        /// <param name="userManager">The ASP.NET Core Identity <see cref="UserManager{TUser}"/> used to manage users and verify passwords.</param>
        /// <param name="tokenService">A service responsible for creating authentication tokens for validated users.</param>
        public AuthService(UserManager<ApplicationUser> userManager, ITokenService tokenService)
        {
            _userManager = userManager;
            _tokenService = tokenService;
        }

        /// <summary>
        /// Attempts to authenticate a user with the provided credentials and returns a response containing
        /// authentication result and a token when successful.
        /// </summary>
        /// <param name="loginRequestDto">The login request containing the user's email (used as username) and password.</param>
        /// <returns>
        /// A <see cref="LoginResponseDto"/> indicating whether authentication succeeded. When authentication
        /// is successful, the response includes a token generated by the configured <see cref="ITokenService"/>.
        /// When authentication fails, the response's <see cref="LoginResponseDto.ErrorMessage"/> contains a reason.
        /// </returns>
        public async Task<LoginResponseDto> LoginAsync(LoginRequestDto loginRequestDto)
        {
            var user = await _userManager.FindByEmailAsync(loginRequestDto.Email);
            if (user == null)
            {
                return new LoginResponseDto { IsAuthenticated = false, ErrorMessage = "Invalid email or password." };
            }
            
            var result = await _userManager.CheckPasswordAsync(user, loginRequestDto.Password);
            if (!result)
            {
                return new LoginResponseDto { IsAuthenticated = false, ErrorMessage = "Invalid email or password." };
            }

            var token = await _tokenService.GetTokenAsync(user);
            return new LoginResponseDto { IsAuthenticated = true, Token = token };
        }

        public async Task<RegisterResponseDto> RegisterAsync(RegisterRequestDto registerRequestDto)
        {
            // Maak een nieuwe ApplicationUser aan met de gegevens uit registerRequestDto
            var newUser = new ApplicationUser
            {
                UserName = registerRequestDto.Username,
                Email = registerRequestDto.Email,
                SecurityStamp = System.Guid.NewGuid().ToString() // SecurityStamp is nodig voor logging out
            };

            // Registreer de nieuwe gebruiker met het opgegeven wachtwoord
            var result = await _userManager.CreateAsync(newUser, registerRequestDto.Password);

            if (result.Succeeded)
            {
                return new RegisterResponseDto
                {
                    IsSuccess = true,
                    Errors = new List<string>() // Geef een lege lijst terug in plaats van null
                };
            }

            // Fout: Verzamel en retourneer de foutmeldingen
            var errors = result.Errors.Select(e => e.Description).ToList();

            return new RegisterResponseDto
            {
                IsSuccess = false,
                Errors = errors
            };
        }
    }
}
